// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGPN6Lj5a0fN3cudS-phyzdL8YzyHmGM',
    appId: '1:610586505769:web:2de902316c0647fd78e238',
    messagingSenderId: '610586505769',
    projectId: 'studia-48762',
    authDomain: 'studia-48762.firebaseapp.com',
    storageBucket: 'studia-48762.firebasestorage.app',
    measurementId: 'G-JQ42CGWYY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCx9JNlybJC9VsncGs9j4l0D8F-B6Qlk0',
    appId: '1:610586505769:android:eb68d1b03efca15278e238',
    messagingSenderId: '610586505769',
    projectId: 'studia-48762',
    storageBucket: 'studia-48762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2tfI5ougSua06VnVmCF6t2Noa2k1b5o',
    appId: '1:610586505769:ios:3a6f0d4afef23e8778e238',
    messagingSenderId: '610586505769',
    projectId: 'studia-48762',
    storageBucket: 'studia-48762.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG2tfI5ougSua06VnVmCF6t2Noa2k1b5o',
    appId: '1:610586505769:ios:3a6f0d4afef23e8778e238',
    messagingSenderId: '610586505769',
    projectId: 'studia-48762',
    storageBucket: 'studia-48762.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnGPN6Lj5a0fN3cudS-phyzdL8YzyHmGM',
    appId: '1:610586505769:web:9692dd53fbfa658b78e238',
    messagingSenderId: '610586505769',
    projectId: 'studia-48762',
    authDomain: 'studia-48762.firebaseapp.com',
    storageBucket: 'studia-48762.firebasestorage.app',
    measurementId: 'G-2Y8490PW1K',
  );
}
